ci:
  autoupdate_schedule: weekly

# https://pre-commit.com/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 0.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 0.0.0
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes"]
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.1.0
    hooks:
      - id: black-jupyter
  - repo: https://github.com/keewis/blackdoc
    rev: 0.0.0
    hooks:
      - id: blackdoc
        additional_dependencies: ["black==26.1.0"]
      - id: blackdoc-autoupdate-black
  - repo: https://github.com/kynan/nbstripout
    rev: 0.0.0
    hooks:
      - id: nbstripout
        args:
          - "--extra-keys=metadata.kernelspec metadata.language_info.version"
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: 0.0.0
    hooks:
      - id: prettier
        args: ["--cache-location=.prettier_cache/cache"]
  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.0.0
    hooks:
      - id: taplo-format
        args: ["--option", "array_auto_collapse=false"]
      - id: taplo-lint
        args: ["--no-schema"]
